/** Bundled CC0 GLTF/GLB paths. See public/models/LICENSE.md. */

export const KIT = {
  roomLarge: '/models/kenney-modular/room-large.glb',
  roomLargeVar: '/models/kenney-modular/room-large-variation.glb',
  roomWide: '/models/kenney-modular/room-wide.glb',
  roomWideVar: '/models/kenney-modular/room-wide-variation.glb',
  roomSmall: '/models/kenney-modular/room-small.glb',
  roomSmallVar: '/models/kenney-modular/room-small-variation.glb',
  corridor: '/models/kenney-modular/corridor.glb',
  corridorWide: '/models/kenney-modular/corridor-wide.glb',
  corridorEnd: '/models/kenney-modular/corridor-end.glb',
  gateDoor: '/models/kenney-modular/gate-door.glb',
  cables: '/models/kenney-modular/cables.glb',

  craftCargoA: '/models/kenney-space/craft_cargoA.glb',
  craftCargoB: '/models/kenney-space/craft_cargoB.glb',
  craftMiner: '/models/kenney-space/craft_miner.glb',
  craftRacer: '/models/kenney-space/craft_racer.glb',
  craftSpeederA: '/models/kenney-space/craft_speederA.glb',
  craftSpeederC: '/models/kenney-space/craft_speederC.glb',
  craftSpeederD: '/models/kenney-space/craft_speederD.glb',
  hangarLargeA: '/models/kenney-space/hangar_largeA.glb',
  hangarLargeB: '/models/kenney-space/hangar_largeB.glb',
  hangarRoundGlass: '/models/kenney-space/hangar_roundGlass.glb',
  hangarRoundA: '/models/kenney-space/hangar_roundA.glb',
  hangarSmallA: '/models/kenney-space/hangar_smallA.glb',
  deskComputer: '/models/kenney-space/desk_computer.glb',
  deskCorner: '/models/kenney-space/desk_computerCorner.glb',
  deskScreen: '/models/kenney-space/desk_computerScreen.glb',
  deskChair: '/models/kenney-space/desk_chair.glb',
  deskChairArms: '/models/kenney-space/desk_chairArms.glb',
  machineGen: '/models/kenney-space/machine_generator.glb',
  machineGenLarge: '/models/kenney-space/machine_generatorLarge.glb',
  machineBarrel: '/models/kenney-space/machine_barrel.glb',
  machineWireless: '/models/kenney-space/machine_wireless.glb',
  pipeStraight: '/models/kenney-space/pipe_straight.glb',
  pipeCorner: '/models/kenney-space/pipe_corner.glb',
  pipeRing: '/models/kenney-space/pipe_ring.glb',
  pipeRingHigh: '/models/kenney-space/pipe_ringHigh.glb',
  platformLarge: '/models/kenney-space/platform_large.glb',
  platformLong: '/models/kenney-space/platform_long.glb',
  platformHigh: '/models/kenney-space/platform_high.glb',
  structure: '/models/kenney-space/structure.glb',
  structureDetailed: '/models/kenney-space/structure_detailed.glb',
  structureClosed: '/models/kenney-space/structure_closed.glb',
  rocketBase: '/models/kenney-space/rocket_baseA.glb',
  rocketFuel: '/models/kenney-space/rocket_fuelA.glb',
  rocketFins: '/models/kenney-space/rocket_finsA.glb',
  rocketTop: '/models/kenney-space/rocket_topA.glb',
  rocketSides: '/models/kenney-space/rocket_sidesA.glb',
  dishLarge: '/models/kenney-space/satelliteDish_large.glb',
  dishDetailed: '/models/kenney-space/satelliteDish_detailed.glb',
  dish: '/models/kenney-space/satelliteDish.glb',
  rover: '/models/kenney-space/rover.glb',
  barrels: '/models/kenney-space/barrels.glb',
  gateComplex: '/models/kenney-space/gate_complex.glb',
  astronautA: '/models/kenney-space/astronautA.glb',
  astronautB: '/models/kenney-space/astronautB.glb',

  wallAstra: '/models/megakit/WallAstra_Straight.gltf',
  wallAstraInner: '/models/megakit/WallAstra_Corner_Square_Inner.gltf',
  wallAstraOuter: '/models/megakit/WallAstra_Corner_Square_Outer.gltf',
  topCables: '/models/megakit/TopCables_Straight.gltf',
  topWindow: '/models/megakit/TopWindow_Straight.gltf',
  topAstra: '/models/megakit/TopAstra_Straight.gltf',
  topPlastic: '/models/megakit/TopPlastic_Straight.gltf',
  bottomMetal: '/models/megakit/BottomMetal_Straight.gltf',
  shortMetal: '/models/megakit/ShortWall_DarkMetal2_Straight.gltf',
  shortPlates: '/models/megakit/ShortWall_MetalPlates_Straight.gltf',
  shortAccent: '/models/megakit/ShortWall_AccentStrip_Straight.gltf',
  shortMetal2: '/models/megakit/ShortWall_Metal2_Straight.gltf',
  floorMetal: '/models/megakit/Platform_Metal.gltf',
  floorDark: '/models/megakit/Platform_DarkPlates.gltf',
  floorSimple: '/models/megakit/Platform_Simple.gltf',
  windowWide: '/models/megakit/Platform_Window_Wide.gltf',
  stairs: '/models/megakit/Platform_Stairs_4WideTall.gltf',
  doorMetal: '/models/megakit/Door_DarkMetal.gltf',
  doorHeavy: '/models/megakit/Door_Metal.gltf',
  doorFrame: '/models/megakit/Door_Frame_A.gltf',
  columnPipes: '/models/megakit/Column_Pipes.gltf',
  columnSupport: '/models/megakit/Column_MetalSupport.gltf',
  columnLarge: '/models/megakit/Column_Large_Straight.gltf',
  columnAstra: '/models/megakit/Column_Astra.gltf',
  columnRound: '/models/megakit/Column_Round.gltf',
  columnHollow: '/models/megakit/Column_Hollow.gltf',
  computer: '/models/megakit/Prop_Computer.gltf',
  decalLogo: '/models/megakit/Decal_Logo.gltf',
  shipImperial: '/models/ships/Imperial.glb',
  shipExecutioner: '/models/ships/Executioner.glb',
  shipChallenger: '/models/ships/Challenger.glb',
  shipInsurgent: '/models/ships/Insurgent.glb',
  shipSpitfire: '/models/ships/Spitfire.glb',
  shipStriker: '/models/ships/Striker.glb',
  shipZenith: '/models/ships/Zenith.glb',
  accessPoint: '/models/megakit/Prop_AccessPoint.gltf',
  cable1: '/models/megakit/Prop_Cable_1.gltf',
  cable3: '/models/megakit/Prop_Cable_3.gltf',
  chest: '/models/megakit/Prop_Chest.gltf',
  crate: '/models/megakit/Prop_Crate4.gltf',
  barrelLarge: '/models/megakit/Prop_Barrel_Large.gltf',
  vent: '/models/megakit/Prop_Vent_Big.gltf',
  fan: '/models/megakit/Prop_Fan_Small.gltf',
  lightWide: '/models/megakit/Prop_Light_Wide.gltf',
  lightFloor: '/models/megakit/Prop_Light_Floor.gltf',
  pipeHolder: '/models/megakit/Prop_PipeHolder.gltf',
} as const;

export type KitName = keyof typeof KIT;

export function kitUrl(name: KitName): string {
  return KIT[name];
}

export function allKitUrls(): string[] {
  return Object.values(KIT);
}
